In [ ]:
import numpy as np
A = np.array([[0,0,1/4,1/2],
              [1/3,0,1/4,0],
              [1/3,1/2,1/4,1/2],
              [1/3,1/2,1/4,0]])
vector = np.array([0,1,0,0])
for i in range(100):
  vector = np.dot(A,vector)
print(vector)

[0.21649485 0.16494845 0.37113402 0.24742268]


In [ ]:
import numpy as np
A = np.array([[0  ,0  ,1/2,0  ,0  ,0  ,0  ,1/8],
              [1/2,0  ,0  ,0  ,0  ,0  ,0  ,1/8],
              [0  ,1/2,0  ,0  ,0  ,1/2,0  ,1/8],
              [0  ,0  ,0  ,0  ,0  ,0  ,0  ,1/8],
              [1/2,1/2,1/2,1  ,0  ,0  ,1/3,1/8],
              [0  ,0  ,0  ,0  ,1/2,0  ,1/3,1/8],
              [0  ,0  ,0  ,0  ,1/2,1/2,0  ,1/8],
              [0  ,0  ,0  ,0  ,0  ,0  ,1/3,1/8]])
p=0.1
B=(1/8)*np.array([[1,1,1,1,1,1,1,1],
                  [1,1,1,1,1,1,1,1],
                  [1,1,1,1,1,1,1,1],
                  [1,1,1,1,1,1,1,1],
                  [1,1,1,1,1,1,1,1],
                  [1,1,1,1,1,1,1,1],
                  [1,1,1,1,1,1,1,1],
                  [1,1,1,1,1,1,1,1],])
M=np.dot(1-p,A)+np.dot(p,B)
vector = np.array([0,1,0,0,0,0,0,0])
for i in range(100):
  vector = np.dot(A,vector)
print(M)
print("\nSteady State Vector is :\n",vector)

[[0.0125 0.0125 0.4625 0.0125 0.0125 0.0125 0.0125 0.125 ]
 [0.4625 0.0125 0.0125 0.0125 0.0125 0.0125 0.0125 0.125 ]
 [0.0125 0.4625 0.0125 0.0125 0.0125 0.4625 0.0125 0.125 ]
 [0.0125 0.0125 0.0125 0.0125 0.0125 0.0125 0.0125 0.125 ]
 [0.4625 0.4625 0.4625 0.9125 0.0125 0.0125 0.3125 0.125 ]
 [0.0125 0.0125 0.0125 0.0125 0.4625 0.0125 0.3125 0.125 ]
 [0.0125 0.0125 0.0125 0.0125 0.4625 0.4625 0.0125 0.125 ]
 [0.0125 0.0125 0.0125 0.0125 0.0125 0.0125 0.3125 0.125 ]]

Steady State Vector is :
 [0.07746479 0.04929577 0.13380282 0.01056338 0.22535211 0.1971831
 0.22183099 0.08450704]


In [ ]:
import numpy as np
A = np.array([[0  ,0  ,1/2,0  ,0  ,0  ,0  ,1/8],
              [1/2,0  ,0  ,0  ,0  ,0  ,0  ,1/8],
              [0  ,1/2,0  ,0  ,0  ,1/2,0  ,1/8],
              [0  ,0  ,0  ,0  ,0  ,0  ,0  ,1/8],
              [1/2,1/2,1/2,1  ,0  ,0  ,1/3,1/8],
              [0  ,0  ,0  ,0  ,1/2,0  ,1/3,1/8],
              [0  ,0  ,0  ,0  ,1/2,1/2,0  ,1/8],
              [0  ,0  ,0  ,0  ,0  ,0  ,1/3,1/8]])
p=0.1
B=(1/8)*np.array([[1,1,1,1,1,1,1,1],
                  [1,1,1,1,1,1,1,1],
                  [1,1,1,1,1,1,1,1],
                  [1,1,1,1,1,1,1,1],
                  [1,1,1,1,1,1,1,1],
                  [1,1,1,1,1,1,1,1],
                  [1,1,1,1,1,1,1,1],
                  [1,1,1,1,1,1,1,1],])
M=(1-p)*A + p*B
print(M)
vector = np.array([0,1,0,0,0,0,0,0])
for i in range(100):
  pvector = np.round(np.dot(M,vector),4)
  print(vector)
  if(pvector == vector).all():
    print(i)
    break
  vector = pvector
print("\nSteady State Vector is :\n",vector)

[[0.0125 0.0125 0.4625 0.0125 0.0125 0.0125 0.0125 0.125 ]
 [0.4625 0.0125 0.0125 0.0125 0.0125 0.0125 0.0125 0.125 ]
 [0.0125 0.4625 0.0125 0.0125 0.0125 0.4625 0.0125 0.125 ]
 [0.0125 0.0125 0.0125 0.0125 0.0125 0.0125 0.0125 0.125 ]
 [0.4625 0.4625 0.4625 0.9125 0.0125 0.0125 0.3125 0.125 ]
 [0.0125 0.0125 0.0125 0.0125 0.4625 0.0125 0.3125 0.125 ]
 [0.0125 0.0125 0.0125 0.0125 0.4625 0.4625 0.0125 0.125 ]
 [0.0125 0.0125 0.0125 0.0125 0.0125 0.0125 0.3125 0.125 ]]
[0 1 0 0 0 0 0 0]
[0.0125 0.0125 0.4625 0.0125 0.4625 0.0125 0.0125 0.0125]
[0.222  0.0195 0.0252 0.0139 0.2483 0.2258 0.2277 0.0177]
[0.0258 0.1144 0.1249 0.0145 0.2153 0.1945 0.2278 0.0828]
[0.078  0.0334 0.1608 0.0218 0.2225 0.187  0.2062 0.0902]
[0.095  0.0577 0.1218 0.0226 0.2266 0.1846 0.2069 0.0845]
[0.0768 0.0648 0.131  0.022  0.2279 0.186  0.207  0.0841]
[0.0809 0.0565 0.1348 0.022  0.2265 0.1866 0.2082 0.0841]
[0.0826 0.0584 0.1314 0.022  0.2267 0.1863 0.2079 0.0844]
[0.0811 0.0592 0.1321 0.022  0.2267 0.1864 0.